// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package qtx

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockEnlistment creates a new instance of MockEnlistment. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEnlistment(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEnlistment {
	mock := &MockEnlistment{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEnlistment is an autogenerated mock type for the Enlistment type
type MockEnlistment struct {
	mock.Mock
}

type MockEnlistment_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEnlistment) EXPECT() *MockEnlistment_Expecter {
	return &MockEnlistment_Expecter{mock: &_m.Mock}
}

// Done provides a mock function for the type MockEnlistment
func (_mock *MockEnlistment) Done() {
	_mock.Called()
	return
}

// MockEnlistment_Done_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Done'
type MockEnlistment_Done_Call struct {
	*mock.Call
}

// Done is a helper method to define mock.On call
func (_e *MockEnlistment_Expecter) Done() *MockEnlistment_Done_Call {
	return &MockEnlistment_Done_Call{Call: _e.mock.On("Done")}
}

func (_c *MockEnlistment_Done_Call) Run(run func()) *MockEnlistment_Done_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEnlistment_Done_Call) Return() *MockEnlistment_Done_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockEnlistment_Done_Call) RunAndReturn(run func()) *MockEnlistment_Done_Call {
	_c.Run(run)
	return _c
}

// NewMockSinglePhaseEnlistment creates a new instance of MockSinglePhaseEnlistment. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSinglePhaseEnlistment(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSinglePhaseEnlistment {
	mock := &MockSinglePhaseEnlistment{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSinglePhaseEnlistment is an autogenerated mock type for the SinglePhaseEnlistment type
type MockSinglePhaseEnlistment struct {
	mock.Mock
}

type MockSinglePhaseEnlistment_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSinglePhaseEnlistment) EXPECT() *MockSinglePhaseEnlistment_Expecter {
	return &MockSinglePhaseEnlistment_Expecter{mock: &_m.Mock}
}

// Aborted provides a mock function for the type MockSinglePhaseEnlistment
func (_mock *MockSinglePhaseEnlistment) Aborted(cause error) {
	_mock.Called(cause)
	return
}

// MockSinglePhaseEnlistment_Aborted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Aborted'
type MockSinglePhaseEnlistment_Aborted_Call struct {
	*mock.Call
}

// Aborted is a helper method to define mock.On call
//   - cause error
func (_e *MockSinglePhaseEnlistment_Expecter) Aborted(cause interface{}) *MockSinglePhaseEnlistment_Aborted_Call {
	return &MockSinglePhaseEnlistment_Aborted_Call{Call: _e.mock.On("Aborted", cause)}
}

func (_c *MockSinglePhaseEnlistment_Aborted_Call) Run(run func(cause error)) *MockSinglePhaseEnlistment_Aborted_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 error
		if args[0] != nil {
			arg0 = args[0].(error)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSinglePhaseEnlistment_Aborted_Call) Return() *MockSinglePhaseEnlistment_Aborted_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSinglePhaseEnlistment_Aborted_Call) RunAndReturn(run func(cause error)) *MockSinglePhaseEnlistment_Aborted_Call {
	_c.Run(run)
	return _c
}

// Committed provides a mock function for the type MockSinglePhaseEnlistment
func (_mock *MockSinglePhaseEnlistment) Committed() {
	_mock.Called()
	return
}

// MockSinglePhaseEnlistment_Committed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Committed'
type MockSinglePhaseEnlistment_Committed_Call struct {
	*mock.Call
}

// Committed is a helper method to define mock.On call
func (_e *MockSinglePhaseEnlistment_Expecter) Committed() *MockSinglePhaseEnlistment_Committed_Call {
	return &MockSinglePhaseEnlistment_Committed_Call{Call: _e.mock.On("Committed")}
}

func (_c *MockSinglePhaseEnlistment_Committed_Call) Run(run func()) *MockSinglePhaseEnlistment_Committed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSinglePhaseEnlistment_Committed_Call) Return() *MockSinglePhaseEnlistment_Committed_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSinglePhaseEnlistment_Committed_Call) RunAndReturn(run func()) *MockSinglePhaseEnlistment_Committed_Call {
	_c.Run(run)
	return _c
}

// NewMockPreparingEnlistment creates a new instance of MockPreparingEnlistment. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPreparingEnlistment(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPreparingEnlistment {
	mock := &MockPreparingEnlistment{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPreparingEnlistment is an autogenerated mock type for the PreparingEnlistment type
type MockPreparingEnlistment struct {
	mock.Mock
}

type MockPreparingEnlistment_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPreparingEnlistment) EXPECT() *MockPreparingEnlistment_Expecter {
	return &MockPreparingEnlistment_Expecter{mock: &_m.Mock}
}

// Done provides a mock function for the type MockPreparingEnlistment
func (_mock *MockPreparingEnlistment) Done() {
	_mock.Called()
	return
}

// MockPreparingEnlistment_Done_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Done'
type MockPreparingEnlistment_Done_Call struct {
	*mock.Call
}

// Done is a helper method to define mock.On call
func (_e *MockPreparingEnlistment_Expecter) Done() *MockPreparingEnlistment_Done_Call {
	return &MockPreparingEnlistment_Done_Call{Call: _e.mock.On("Done")}
}

func (_c *MockPreparingEnlistment_Done_Call) Run(run func()) *MockPreparingEnlistment_Done_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPreparingEnlistment_Done_Call) Return() *MockPreparingEnlistment_Done_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockPreparingEnlistment_Done_Call) RunAndReturn(run func()) *MockPreparingEnlistment_Done_Call {
	_c.Run(run)
	return _c
}

// ForceRollback provides a mock function for the type MockPreparingEnlistment
func (_mock *MockPreparingEnlistment) ForceRollback(cause error) {
	_mock.Called(cause)
	return
}

// MockPreparingEnlistment_ForceRollback_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ForceRollback'
type MockPreparingEnlistment_ForceRollback_Call struct {
	*mock.Call
}

// ForceRollback is a helper method to define mock.On call
//   - cause error
func (_e *MockPreparingEnlistment_Expecter) ForceRollback(cause interface{}) *MockPreparingEnlistment_ForceRollback_Call {
	return &MockPreparingEnlistment_ForceRollback_Call{Call: _e.mock.On("ForceRollback", cause)}
}

func (_c *MockPreparingEnlistment_ForceRollback_Call) Run(run func(cause error)) *MockPreparingEnlistment_ForceRollback_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 error
		if args[0] != nil {
			arg0 = args[0].(error)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPreparingEnlistment_ForceRollback_Call) Return() *MockPreparingEnlistment_ForceRollback_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockPreparingEnlistment_ForceRollback_Call) RunAndReturn(run func(cause error)) *MockPreparingEnlistment_ForceRollback_Call {
	_c.Run(run)
	return _c
}

// Prepared provides a mock function for the type MockPreparingEnlistment
func (_mock *MockPreparingEnlistment) Prepared() {
	_mock.Called()
	return
}

// MockPreparingEnlistment_Prepared_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Prepared'
type MockPreparingEnlistment_Prepared_Call struct {
	*mock.Call
}

// Prepared is a helper method to define mock.On call
func (_e *MockPreparingEnlistment_Expecter) Prepared() *MockPreparingEnlistment_Prepared_Call {
	return &MockPreparingEnlistment_Prepared_Call{Call: _e.mock.On("Prepared")}
}

func (_c *MockPreparingEnlistment_Prepared_Call) Run(run func()) *MockPreparingEnlistment_Prepared_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPreparingEnlistment_Prepared_Call) Return() *MockPreparingEnlistment_Prepared_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockPreparingEnlistment_Prepared_Call) RunAndReturn(run func()) *MockPreparingEnlistment_Prepared_Call {
	_c.Run(run)
	return _c
}

// NewMockEnlistmentNotification creates a new instance of MockEnlistmentNotification. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEnlistmentNotification(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEnlistmentNotification {
	mock := &MockEnlistmentNotification{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEnlistmentNotification is an autogenerated mock type for the EnlistmentNotification type
type MockEnlistmentNotification struct {
	mock.Mock
}

type MockEnlistmentNotification_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEnlistmentNotification) EXPECT() *MockEnlistmentNotification_Expecter {
	return &MockEnlistmentNotification_Expecter{mock: &_m.Mock}
}

// Commit provides a mock function for the type MockEnlistmentNotification
func (_mock *MockEnlistmentNotification) Commit(ctx context.Context, enl Enlistment) {
	_mock.Called(ctx, enl)
	return
}

// MockEnlistmentNotification_Commit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Commit'
type MockEnlistmentNotification_Commit_Call struct {
	*mock.Call
}

// Commit is a helper method to define mock.On call
//   - ctx context.Context
//   - enl Enlistment
func (_e *MockEnlistmentNotification_Expecter) Commit(ctx interface{}, enl interface{}) *MockEnlistmentNotification_Commit_Call {
	return &MockEnlistmentNotification_Commit_Call{Call: _e.mock.On("Commit", ctx, enl)}
}

func (_c *MockEnlistmentNotification_Commit_Call) Run(run func(ctx context.Context, enl Enlistment)) *MockEnlistmentNotification_Commit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 Enlistment
		if args[1] != nil {
			arg1 = args[1].(Enlistment)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEnlistmentNotification_Commit_Call) Return() *MockEnlistmentNotification_Commit_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockEnlistmentNotification_Commit_Call) RunAndReturn(run func(ctx context.Context, enl Enlistment)) *MockEnlistmentNotification_Commit_Call {
	_c.Run(run)
	return _c
}

// Prepare provides a mock function for the type MockEnlistmentNotification
func (_mock *MockEnlistmentNotification) Prepare(ctx context.Context, enl PreparingEnlistment) {
	_mock.Called(ctx, enl)
	return
}

// MockEnlistmentNotification_Prepare_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Prepare'
type MockEnlistmentNotification_Prepare_Call struct {
	*mock.Call
}

// Prepare is a helper method to define mock.On call
//   - ctx context.Context
//   - enl PreparingEnlistment
func (_e *MockEnlistmentNotification_Expecter) Prepare(ctx interface{}, enl interface{}) *MockEnlistmentNotification_Prepare_Call {
	return &MockEnlistmentNotification_Prepare_Call{Call: _e.mock.On("Prepare", ctx, enl)}
}

func (_c *MockEnlistmentNotification_Prepare_Call) Run(run func(ctx context.Context, enl PreparingEnlistment)) *MockEnlistmentNotification_Prepare_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 PreparingEnlistment
		if args[1] != nil {
			arg1 = args[1].(PreparingEnlistment)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEnlistmentNotification_Prepare_Call) Return() *MockEnlistmentNotification_Prepare_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockEnlistmentNotification_Prepare_Call) RunAndReturn(run func(ctx context.Context, enl PreparingEnlistment)) *MockEnlistmentNotification_Prepare_Call {
	_c.Run(run)
	return _c
}

// Rollback provides a mock function for the type MockEnlistmentNotification
func (_mock *MockEnlistmentNotification) Rollback(ctx context.Context, enl Enlistment) {
	_mock.Called(ctx, enl)
	return
}

// MockEnlistmentNotification_Rollback_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Rollback'
type MockEnlistmentNotification_Rollback_Call struct {
	*mock.Call
}

// Rollback is a helper method to define mock.On call
//   - ctx context.Context
//   - enl Enlistment
func (_e *MockEnlistmentNotification_Expecter) Rollback(ctx interface{}, enl interface{}) *MockEnlistmentNotification_Rollback_Call {
	return &MockEnlistmentNotification_Rollback_Call{Call: _e.mock.On("Rollback", ctx, enl)}
}

func (_c *MockEnlistmentNotification_Rollback_Call) Run(run func(ctx context.Context, enl Enlistment)) *MockEnlistmentNotification_Rollback_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 Enlistment
		if args[1] != nil {
			arg1 = args[1].(Enlistment)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEnlistmentNotification_Rollback_Call) Return() *MockEnlistmentNotification_Rollback_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockEnlistmentNotification_Rollback_Call) RunAndReturn(run func(ctx context.Context, enl Enlistment)) *MockEnlistmentNotification_Rollback_Call {
	_c.Run(run)
	return _c
}

// NewMockSinglePhaseNotification creates a new instance of MockSinglePhaseNotification. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSinglePhaseNotification(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSinglePhaseNotification {
	mock := &MockSinglePhaseNotification{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSinglePhaseNotification is an autogenerated mock type for the SinglePhaseNotification type
type MockSinglePhaseNotification struct {
	mock.Mock
}

type MockSinglePhaseNotification_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSinglePhaseNotification) EXPECT() *MockSinglePhaseNotification_Expecter {
	return &MockSinglePhaseNotification_Expecter{mock: &_m.Mock}
}

// Commit provides a mock function for the type MockSinglePhaseNotification
func (_mock *MockSinglePhaseNotification) Commit(ctx context.Context, enl Enlistment) {
	_mock.Called(ctx, enl)
	return
}

// MockSinglePhaseNotification_Commit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Commit'
type MockSinglePhaseNotification_Commit_Call struct {
	*mock.Call
}

// Commit is a helper method to define mock.On call
//   - ctx context.Context
//   - enl Enlistment
func (_e *MockSinglePhaseNotification_Expecter) Commit(ctx interface{}, enl interface{}) *MockSinglePhaseNotification_Commit_Call {
	return &MockSinglePhaseNotification_Commit_Call{Call: _e.mock.On("Commit", ctx, enl)}
}

func (_c *MockSinglePhaseNotification_Commit_Call) Run(run func(ctx context.Context, enl Enlistment)) *MockSinglePhaseNotification_Commit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 Enlistment
		if args[1] != nil {
			arg1 = args[1].(Enlistment)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSinglePhaseNotification_Commit_Call) Return() *MockSinglePhaseNotification_Commit_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSinglePhaseNotification_Commit_Call) RunAndReturn(run func(ctx context.Context, enl Enlistment)) *MockSinglePhaseNotification_Commit_Call {
	_c.Run(run)
	return _c
}

// Prepare provides a mock function for the type MockSinglePhaseNotification
func (_mock *MockSinglePhaseNotification) Prepare(ctx context.Context, enl PreparingEnlistment) {
	_mock.Called(ctx, enl)
	return
}

// MockSinglePhaseNotification_Prepare_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Prepare'
type MockSinglePhaseNotification_Prepare_Call struct {
	*mock.Call
}

// Prepare is a helper method to define mock.On call
//   - ctx context.Context
//   - enl PreparingEnlistment
func (_e *MockSinglePhaseNotification_Expecter) Prepare(ctx interface{}, enl interface{}) *MockSinglePhaseNotification_Prepare_Call {
	return &MockSinglePhaseNotification_Prepare_Call{Call: _e.mock.On("Prepare", ctx, enl)}
}

func (_c *MockSinglePhaseNotification_Prepare_Call) Run(run func(ctx context.Context, enl PreparingEnlistment)) *MockSinglePhaseNotification_Prepare_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 PreparingEnlistment
		if args[1] != nil {
			arg1 = args[1].(PreparingEnlistment)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSinglePhaseNotification_Prepare_Call) Return() *MockSinglePhaseNotification_Prepare_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSinglePhaseNotification_Prepare_Call) RunAndReturn(run func(ctx context.Context, enl PreparingEnlistment)) *MockSinglePhaseNotification_Prepare_Call {
	_c.Run(run)
	return _c
}

// Rollback provides a mock function for the type MockSinglePhaseNotification
func (_mock *MockSinglePhaseNotification) Rollback(ctx context.Context, enl Enlistment) {
	_mock.Called(ctx, enl)
	return
}

// MockSinglePhaseNotification_Rollback_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Rollback'
type MockSinglePhaseNotification_Rollback_Call struct {
	*mock.Call
}

// Rollback is a helper method to define mock.On call
//   - ctx context.Context
//   - enl Enlistment
func (_e *MockSinglePhaseNotification_Expecter) Rollback(ctx interface{}, enl interface{}) *MockSinglePhaseNotification_Rollback_Call {
	return &MockSinglePhaseNotification_Rollback_Call{Call: _e.mock.On("Rollback", ctx, enl)}
}

func (_c *MockSinglePhaseNotification_Rollback_Call) Run(run func(ctx context.Context, enl Enlistment)) *MockSinglePhaseNotification_Rollback_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 Enlistment
		if args[1] != nil {
			arg1 = args[1].(Enlistment)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSinglePhaseNotification_Rollback_Call) Return() *MockSinglePhaseNotification_Rollback_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSinglePhaseNotification_Rollback_Call) RunAndReturn(run func(ctx context.Context, enl Enlistment)) *MockSinglePhaseNotification_Rollback_Call {
	_c.Run(run)
	return _c
}

// SinglePhaseCommit provides a mock function for the type MockSinglePhaseNotification
func (_mock *MockSinglePhaseNotification) SinglePhaseCommit(ctx context.Context, enl SinglePhaseEnlistment) {
	_mock.Called(ctx, enl)
	return
}

// MockSinglePhaseNotification_SinglePhaseCommit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SinglePhaseCommit'
type MockSinglePhaseNotification_SinglePhaseCommit_Call struct {
	*mock.Call
}

// SinglePhaseCommit is a helper method to define mock.On call
//   - ctx context.Context
//   - enl SinglePhaseEnlistment
func (_e *MockSinglePhaseNotification_Expecter) SinglePhaseCommit(ctx interface{}, enl interface{}) *MockSinglePhaseNotification_SinglePhaseCommit_Call {
	return &MockSinglePhaseNotification_SinglePhaseCommit_Call{Call: _e.mock.On("SinglePhaseCommit", ctx, enl)}
}

func (_c *MockSinglePhaseNotification_SinglePhaseCommit_Call) Run(run func(ctx context.Context, enl SinglePhaseEnlistment)) *MockSinglePhaseNotification_SinglePhaseCommit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 SinglePhaseEnlistment
		if args[1] != nil {
			arg1 = args[1].(SinglePhaseEnlistment)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSinglePhaseNotification_SinglePhaseCommit_Call) Return() *MockSinglePhaseNotification_SinglePhaseCommit_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSinglePhaseNotification_SinglePhaseCommit_Call) RunAndReturn(run func(ctx context.Context, enl SinglePhaseEnlistment)) *MockSinglePhaseNotification_SinglePhaseCommit_Call {
	_c.Run(run)
	return _c
}

// NewMockTransaction creates a new instance of MockTransaction. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTransaction(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTransaction {
	mock := &MockTransaction{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTransaction is an autogenerated mock type for the Transaction type
type MockTransaction struct {
	mock.Mock
}

type MockTransaction_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTransaction) EXPECT() *MockTransaction_Expecter {
	return &MockTransaction_Expecter{mock: &_m.Mock}
}

// EnlistTheOnlyDurable provides a mock function for the type MockTransaction
func (_mock *MockTransaction) EnlistTheOnlyDurable(trm SinglePhaseNotification) error {
	ret := _mock.Called(trm)

	if len(ret) == 0 {
		panic("no return value specified for EnlistTheOnlyDurable")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(SinglePhaseNotification) error); ok {
		r0 = returnFunc(trm)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTransaction_EnlistTheOnlyDurable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnlistTheOnlyDurable'
type MockTransaction_EnlistTheOnlyDurable_Call struct {
	*mock.Call
}

// EnlistTheOnlyDurable is a helper method to define mock.On call
//   - trm SinglePhaseNotification
func (_e *MockTransaction_Expecter) EnlistTheOnlyDurable(trm interface{}) *MockTransaction_EnlistTheOnlyDurable_Call {
	return &MockTransaction_EnlistTheOnlyDurable_Call{Call: _e.mock.On("EnlistTheOnlyDurable", trm)}
}

func (_c *MockTransaction_EnlistTheOnlyDurable_Call) Run(run func(trm SinglePhaseNotification)) *MockTransaction_EnlistTheOnlyDurable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 SinglePhaseNotification
		if args[0] != nil {
			arg0 = args[0].(SinglePhaseNotification)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTransaction_EnlistTheOnlyDurable_Call) Return(err error) *MockTransaction_EnlistTheOnlyDurable_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTransaction_EnlistTheOnlyDurable_Call) RunAndReturn(run func(trm SinglePhaseNotification) error) *MockTransaction_EnlistTheOnlyDurable_Call {
	_c.Call.Return(run)
	return _c
}

// EnlistVolatile provides a mock function for the type MockTransaction
func (_mock *MockTransaction) EnlistVolatile(trm EnlistmentNotification) error {
	ret := _mock.Called(trm)

	if len(ret) == 0 {
		panic("no return value specified for EnlistVolatile")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(EnlistmentNotification) error); ok {
		r0 = returnFunc(trm)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTransaction_EnlistVolatile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnlistVolatile'
type MockTransaction_EnlistVolatile_Call struct {
	*mock.Call
}

// EnlistVolatile is a helper method to define mock.On call
//   - trm EnlistmentNotification
func (_e *MockTransaction_Expecter) EnlistVolatile(trm interface{}) *MockTransaction_EnlistVolatile_Call {
	return &MockTransaction_EnlistVolatile_Call{Call: _e.mock.On("EnlistVolatile", trm)}
}

func (_c *MockTransaction_EnlistVolatile_Call) Run(run func(trm EnlistmentNotification)) *MockTransaction_EnlistVolatile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 EnlistmentNotification
		if args[0] != nil {
			arg0 = args[0].(EnlistmentNotification)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTransaction_EnlistVolatile_Call) Return(err error) *MockTransaction_EnlistVolatile_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTransaction_EnlistVolatile_Call) RunAndReturn(run func(trm EnlistmentNotification) error) *MockTransaction_EnlistVolatile_Call {
	_c.Call.Return(run)
	return _c
}

// Rollback provides a mock function for the type MockTransaction
func (_mock *MockTransaction) Rollback(context1 context.Context) error {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for Rollback")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(context1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTransaction_Rollback_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Rollback'
type MockTransaction_Rollback_Call struct {
	*mock.Call
}

// Rollback is a helper method to define mock.On call
//   - context1 context.Context
func (_e *MockTransaction_Expecter) Rollback(context1 interface{}) *MockTransaction_Rollback_Call {
	return &MockTransaction_Rollback_Call{Call: _e.mock.On("Rollback", context1)}
}

func (_c *MockTransaction_Rollback_Call) Run(run func(context1 context.Context)) *MockTransaction_Rollback_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTransaction_Rollback_Call) Return(err error) *MockTransaction_Rollback_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTransaction_Rollback_Call) RunAndReturn(run func(context1 context.Context) error) *MockTransaction_Rollback_Call {
	_c.Call.Return(run)
	return _c
}
